# Generated by Django 4.1 on 2022-09-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_user_name_alter_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_type", models.CharField(max_length=100)),
                ("post_title", models.CharField(max_length=200)),
                ("post_image", models.CharField(max_length=200)),
                ("post_body", models.TextField()),
            ],
        ),
    ]
