# Generated by Django 4.1 on 2022-09-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_remove_post_post_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("title_tag", models.TextField()),
                ("brand_title_tag_postfix", models.BooleanField()),
                ("meta_description", models.CharField(max_length=255)),
                ("featured_image", models.CharField(max_length=200)),
                ("noindex", models.BooleanField()),
            ],
        ),
    ]
