# Generated by Django 4.1 on 2022-09-19 12:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="body",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="article", name="title", field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="article",
            name="title_tag",
            field=models.CharField(max_length=100),
        ),
    ]
